### ISSUE TITLE
Strategy for supporting plugins

### ISSUE THREAD

**Issue by mwisner** [joshuairl/ember-cli-videojs-shim#2]
I see that there is an open todo for supporting plugins, I'm just curious if there was any initial strategies or theories on how to go about accomplishing that?

I'm definitely interested in helping in anyway I can with this. My personal use cases will need https://github.com/videojs/videojs-contrib-dash as well as video js itself

**Comment by mwisner** [comment]
Based on a few other examples in the Ember ecosystem, it looks like most of the the "plugins" are usually a separate package... (ember-simple-auth, ember-deploy, ember-bootstrap)

So I went ahead and gave that a shot for my use case. Ended up working pretty well... 

https://github.com/mwisner/ember-videojs-dash

**Comment by jfrux** [comment]
Right, it might need a shim for each plugin.
