### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mwisner** [joshuairl/ember-cli-videojs-shim#5]
Hi,

Once #4 gets merged in, would you mind rolling a new release?

**Comment by jfrux** [comment]
Absolutely!
I'm out of the office until tomorrow but will set a reminder to publish first thing.

Thanks for your work!

**Comment by jfrux** [comment]
@mwisner FYI, Pushed this out to NPM so it should be good to go now.

Sorry for the delay!

**Comment by mwisner** [comment]
Hey @joshuairl, 

Sorry to be such a hassle... Was wondering if you'd mind rolling a 0.1.1 release? I finally have some free time after a few hectic weeks and I am hoping to finish up https://github.com/IvyApp/ivy-videojs/pull/28.

**Comment by jfrux** [comment]
@mwisner I don't mind, not a hassle at all.
What would be going into the 0.1.1?

**Comment by mwisner** [comment]
@joshuairl I think it's just this one bug fix: https://github.com/joshuairl/ember-cli-videojs-shim/pull/6

**Comment by jfrux** [comment]
Done!
